[[redirects]]
  from = "https://opwebdev.com/*"
  to = "https://www.opwebdev.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://www.opwebdev.com/api/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"